// frontend-react/src/components/Stats.tsx
import { useState } from "react";
import { Link } from "react-router-dom";
import { useApi } from "../hooks/useApi";
import { getPlayerAvatar } from "../utils/assets";
import type { Season } from "../types";

interface PlayerStats {
  player_id: number;
  gamertag: string;
  team_abbr: string;
  season_kd: number;
  season_kills: number;
  season_deaths: number;
  season_assists: number;
}

interface StatsResponse {
  players: PlayerStats[];
  count: number;
}

const Stats = () => {
  const [selectedSeasonId, setSelectedSeasonId] = useState<string>("");

  const { data: seasons } = useApi<Season[]>("/api/v1/seasons");

  const statsUrl = selectedSeasonId
    ? `/api/v1/stats/all-kd-by-tournament?season_id=${selectedSeasonId}`
    : "/api/v1/stats/all-kd-by-tournament";

  const { data: statsData, loading, error } = useApi<StatsResponse>(statsUrl);

  const players = [...(statsData?.players ?? [])].sort(
    (a, b) => b.season_kd - a.season_kd
  );

  const selectedSeason = seasons?.find(
    (s) => String(s.id) === selectedSeasonId
  );

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 mb-8">
          <div>
            <h1 className="text-4xl font-bold text-black">K/D LEADERBOARD</h1>
            {selectedSeason && (
              <p className="text-[#6B7280] mt-1">{selectedSeason.name}</p>
            )}
          </div>

          {/* Season selector */}
          <select
            value={selectedSeasonId}
            onChange={(e) => setSelectedSeasonId(e.target.value)}
            className="border border-gray-300 px-4 py-2 text-sm text-black bg-white focus:outline-none focus:border-black"
          >
            <option value="">All Seasons</option>
            {seasons?.map((s) => (
              <option key={s.id} value={String(s.id)}>
                {s.game_title}
              </option>
            ))}
          </select>
        </div>

        {loading && <p className="text-[#6B7280]">Loading statistics...</p>}

        {error && <p className="text-[#555555]">Error: {error}</p>}

        {!loading && !error && (
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-300">
                  <th className="text-left py-4 text-[#6B7280] text-sm uppercase tracking-wider w-12">
                    Rank
                  </th>
                  <th className="text-left py-4 text-[#6B7280] text-sm uppercase tracking-wider">
                    Player
                  </th>
                  <th className="text-left py-4 text-[#6B7280] text-sm uppercase tracking-wider">
                    Team
                  </th>
                  <th className="text-right py-4 text-[#6B7280] text-sm uppercase tracking-wider">
                    K/D
                  </th>
                  <th className="text-right py-4 text-[#6B7280] text-sm uppercase tracking-wider">
                    Kills
                  </th>
                  <th className="text-right py-4 text-[#6B7280] text-sm uppercase tracking-wider">
                    Deaths
                  </th>
                </tr>
              </thead>
              <tbody>
                {players.map((player, index) => (
                  <tr key={player.player_id} className="border-b border-gray-300">
                    <td className="py-4 text-[#6B7280] text-sm">{index + 1}</td>
                    <td className="py-4">
                      <div className="flex items-center gap-3">
                        <img
                          src={getPlayerAvatar(player.gamertag)}
                          alt={player.gamertag}
                          className="w-8 h-8 rounded-full object-cover"
                        />
                        <Link
                          to={`/players/${player.player_id}`}
                          className="font-semibold text-black hover:underline"
                        >
                          {player.gamertag}
                        </Link>
                      </div>
                    </td>
                    <td className="py-4 text-[#6B7280]">
                      {player.team_abbr || "—"}
                    </td>
                    <td className="py-4 text-right font-bold text-black">
                      {player.season_kd?.toFixed(2) ?? "0.00"}
                    </td>
                    <td className="py-4 text-right text-[#6B7280]">
                      {player.season_kills?.toLocaleString() ?? "0"}
                    </td>
                    <td className="py-4 text-right text-[#6B7280]">
                      {player.season_deaths?.toLocaleString() ?? "0"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {players.length === 0 && (
              <p className="text-center text-[#6B7280] py-12">
                No stats available for this season.
              </p>
            )}
          </div>
        )}

        <p className="mt-8 text-[#6B7280] text-sm">
          {players.length} players
        </p>
      </div>
    </div>
  );
};

export default Stats;

// frontend/src/routes/stats/+page.svelte
<script lang="ts">
	import type { PlayerStats } from '$lib/api';
	
	let { data } = $props();
	
	// Use $derived for reactive access to data properties
	const statsData = $derived(data.statsData);
	const error = $derived(data.error as string | null);
	
	// Get players array and sort by K/D
	const players = $derived(
		(statsData?.players || [])
			.slice()
			.sort((a: PlayerStats, b: PlayerStats) => b.season_kd - a.season_kd)
	);
</script>

<svelte:head>
	<title>K/D Leaderboard - CDLYTICS</title>
</svelte:head>

<div class="min-h-screen">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<h1 class="text-4xl font-bold mb-8 pb-4">K/D LEADERBOARD</h1>
		
		{#if error}
			<p class="text-red-500">{error}</p>
		{:else}
			<div class="overflow-x-auto">
				<table class="w-full">
					<thead>
						<tr class="border-b border-theme">
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider w-16">
								Rank
							</th>
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Player
							</th>
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Team
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								K/D
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Kills
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Deaths
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Assists
							</th>
						</tr>
					</thead>
					<tbody>
						{#each players as player, index (player.player_id)}
							<tr class="border-b border-theme hover:bg-theme-secondary/50 transition-colors">
								<td class="py-4 text-theme-secondary">{index + 1}</td>
								<td class="py-4">
									<a 
										href="/players/{player.player_id}" 
										class="font-semibold hover:opacity-70 transition-opacity"
									>
										{player.gamertag}
									</a>
								</td>
								<td class="py-4 text-theme-secondary">
									{player.team_abbr || '—'}
								</td>
								<td class="py-4 text-right font-bold">
									{player.season_kd?.toFixed(2) || '0.00'}
								</td>
								<td class="py-4 text-right text-theme-secondary">
									{player.season_kills?.toLocaleString() || '0'}
								</td>
								<td class="py-4 text-right text-theme-secondary">
									{player.season_deaths?.toLocaleString() || '0'}
								</td>
								<td class="py-4 text-right text-theme-secondary">
									{player.season_assists?.toLocaleString() || '0'}
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
			
			<p class="mt-8 text-theme-secondary text-sm">
				Total Players: {players.length}
			</p>
		{/if}
	</div>
</div>
