// frontend/src/routes/stats/+page.svelte
<script lang="ts">
	import type { PlayerStats } from '$lib/api';
	
	let { data } = $props();
	
	// Use $derived for reactive access to data properties
	const statsData = $derived(data.statsData);
	const error = $derived(data.error as string | null);
	
	// Get players array and sort by K/D
	const players = $derived(
		(statsData?.players || [])
			.slice()
			.sort((a: PlayerStats, b: PlayerStats) => b.season_kd - a.season_kd)
	);
</script>

<svelte:head>
	<title>K/D Leaderboard - CDLYTICS</title>
</svelte:head>

<div class="min-h-screen">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<h1 class="text-4xl font-bold mb-8 pb-4">K/D LEADERBOARD</h1>
		
		{#if error}
			<p class="text-red-500">{error}</p>
		{:else}
			<div class="overflow-x-auto">
				<table class="w-full">
					<thead>
						<tr class="border-b border-theme">
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider w-16">
								Rank
							</th>
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Player
							</th>
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Team
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								K/D
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Kills
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Deaths
							</th>
							<th class="text-right py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Assists
							</th>
						</tr>
					</thead>
					<tbody>
						{#each players as player, index (player.player_id)}
							<tr class="border-b border-theme hover:bg-theme-secondary/50 transition-colors">
								<td class="py-4 text-theme-secondary">{index + 1}</td>
								<td class="py-4">
									<a 
										href="/players/{player.player_id}" 
										class="font-semibold hover:opacity-70 transition-opacity"
									>
										{player.gamertag}
									</a>
								</td>
								<td class="py-4 text-theme-secondary">
									{player.team_abbr || '—'}
								</td>
								<td class="py-4 text-right font-bold">
									{player.season_kd?.toFixed(2) || '0.00'}
								</td>
								<td class="py-4 text-right text-theme-secondary">
									{player.season_kills?.toLocaleString() || '0'}
								</td>
								<td class="py-4 text-right text-theme-secondary">
									{player.season_deaths?.toLocaleString() || '0'}
								</td>
								<td class="py-4 text-right text-theme-secondary">
									{player.season_assists?.toLocaleString() || '0'}
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
			
			<p class="mt-8 text-theme-secondary text-sm">
				Total Players: {players.length}
			</p>
		{/if}
	</div>
</div>

// frontend/src/components/Stats.tsx
import { Link } from "react-router-dom";
import { useApi } from "../hooks/useApi";

interface PlayerStats {
  player_id: number;
  gamertag: string;
  team_abbr: string;
  season_kd: number;
  season_kills: number;
  season_deaths: number;
  season_assists: number;
}

const Stats = () => {
  const {
    data: statsData,
    loading,
    error,
  } = useApi<any>("/api/v1/stats/all-kd-by-tournament");

  if (loading) {
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <p className="text-gray-400">Loading statistics...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <p className="text-red-400">Error: {error}</p>
        <p className="text-gray-400 text-sm mt-2">
          Backend: http://localhost:8080/api/v1/stats/all-kd-by-tournament
        </p>
      </div>
    );
  }

  // Handle the correct response structure
  const players: PlayerStats[] = statsData?.players || [];

  // Sort by K/D ratio
  const sortedPlayers = [...players].sort((a, b) => b.season_kd - a.season_kd);

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-4xl font-bold mb-8 pb-4">K/D LEADERBOARD</h1>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-gray-800">
              <th className="text-left py-4 text-gray-400 text-sm uppercase tracking-wider w-16">
                Rank
              </th>
              <th className="text-left py-4 text-gray-400 text-sm uppercase tracking-wider">
                Player
              </th>
              <th className="text-left py-4 text-gray-400 text-sm uppercase tracking-wider">
                Team
              </th>
              <th className="text-right py-4 text-gray-400 text-sm uppercase tracking-wider">
                K/D
              </th>
              <th className="text-right py-4 text-gray-400 text-sm uppercase tracking-wider">
                Kills
              </th>
              <th className="text-right py-4 text-gray-400 text-sm uppercase tracking-wider">
                Deaths
              </th>
              <th className="text-right py-4 text-gray-400 text-sm uppercase tracking-wider">
                Assists
              </th>
            </tr>
          </thead>
          <tbody>
            {sortedPlayers.map((player, index) => (
              <tr
                key={player.player_id}
                className="border-b border-gray-900 hover:bg-gray-950 transition-colors"
              >
                <td className="py-4 text-gray-400">{index + 1}</td>
                <td className="py-4">
                  <Link
                    to={`/players/${player.player_id}`}
                    className="font-semibold hover:text-gray-400"
                  >
                    {player.gamertag}
                  </Link>
                </td>
                <td className="py-4 text-gray-400">
                  {player.team_abbr || "—"}
                </td>
                <td className="py-4 text-right font-bold">
                  {player.season_kd?.toFixed(2) || "0.00"}
                </td>
                <td className="py-4 text-right text-gray-400">
                  {player.season_kills?.toLocaleString() || "0"}
                </td>
                <td className="py-4 text-right text-gray-400">
                  {player.season_deaths?.toLocaleString() || "0"}
                </td>
                <td className="py-4 text-right text-gray-400">
                  {player.season_assists?.toLocaleString() || "0"}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-8 text-gray-400 text-sm">
        Total Players: {sortedPlayers.length}
      </p>
    </div>
  );
};

export default Stats;
