// frontend/src/components/Transfers.tsx
import { useApi } from "../hooks/useApi";
import { Link } from "react-router-dom";
import type { PlayerTransfer } from "../types";

interface TransfersResponse {
  transfers: PlayerTransfer[];
  count: number;
  timestamp?: number;
}

const Transfers = () => {
  const { data: response, loading, error } = useApi<TransfersResponse>(
    "/api/v1/transfers"
  );
  
  const transfers = response?.transfers || [];

  // Format date for display
  const formatDate = (dateString: string) => {
    try {
      const date = new Date(dateString);
      return date.toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    } catch {
      return dateString;
    }
  };

  // Get transfer type badge color
  const getTransferTypeColor = (type: string) => {
    switch (type.toLowerCase()) {
      case "signing":
        return "bg-black/10 text-black";
      case "release":
        return "bg-[#6B7280]/20 text-[#6B7280]";
      case "trade":
        return "bg-black/10 text-black";
      default:
        return "bg-gray-200 text-black";
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <p className="text-[#6B7280]">Loading transfers...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <p className="text-[#555555]">Error: {error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="text-4xl font-bold mb-8 pb-4 text-black">TRANSFERS</h1>

        <div className="space-y-4">
          {transfers && transfers.length > 0 ? (
            transfers.map((transfer) => (
              <div
                key={transfer.id}
                className="bg-[#F4F4F5] p-6 shadow-md shadow-[rgba(0,0,0,0.1)]"
              >
                <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                  {/* Left: Player Info */}
                  <div className="flex items-center space-x-4 flex-1">
                    {transfer.player?.avatar_url && (
                      <img
                        src={transfer.player.avatar_url}
                        alt={transfer.player.gamertag}
                        className="w-16 h-16 object-cover shadow-sm"
                      />
                    )}
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <Link
                          to={`/players/${transfer.player_id}`}
                          className="text-xl font-bold text-black"
                        >
                          {transfer.player?.gamertag || "Unknown Player"}
                        </Link>
                        <span
                          className={`px-3 py-1 text-xs font-medium ${getTransferTypeColor(
                            transfer.transfer_type
                          )}`}
                        >
                          {transfer.transfer_type.toUpperCase()}
                        </span>
                      </div>

                      {/* Transfer Path */}
                      <div className="flex items-center gap-2 text-sm">
                        <span className="text-[#6B7280]">
                          {transfer.from_team?.name || "Free Agent"}
                        </span>
                        <span className="text-black">→</span>
                        <span className="font-semibold text-black">
                          {transfer.to_team?.name || "Free Agent"}
                        </span>
                      </div>
                    </div>
                  </div>

                  {/* Right: Details */}
                  <div className="flex flex-col md:items-end gap-2 text-sm">
                    <div className="flex items-center gap-4 text-[#6B7280]">
                      {transfer.role && (
                        <span className="uppercase tracking-wider">
                          {transfer.role}
                        </span>
                      )}
                      {transfer.season && (
                        <span className="uppercase tracking-wider">
                          {transfer.season}
                        </span>
                      )}
                    </div>
                    <p className="text-[#6B7280]">
                      {formatDate(transfer.transfer_date)}
                    </p>
                  </div>
                </div>

                {/* Description if available */}
                {transfer.description && (
                  <div className="mt-4 pt-4 border-t border-gray-300">
                    <p className="text-sm text-[#555555]">
                      {transfer.description}
                    </p>
                  </div>
                )}
              </div>
            ))
          ) : (
            <div className="bg-[#F4F4F5] p-8 text-center">
              <p className="text-[#6B7280]">No transfers available</p>
            </div>
          )}
        </div>

        <p className="mt-8 text-[#6B7280] text-sm">
          Total Transfers: {transfers?.length || 0}
        </p>
      </div>
    </div>
  );
};

export default Transfers;

// frontend/src/routes/transfers/+page.svelte
<script lang="ts">
	import type { PlayerTransfer } from '$lib/api';
	
	let { data } = $props();
	
	// Use $derived for reactive access to data properties
	const transfers = $derived(data.transfers as PlayerTransfer[]);
	const error = $derived(data.error as string | null);
	
	// Format date for display
	function formatDate(dateString: string): string {
		try {
			const date = new Date(dateString);
			return date.toLocaleDateString('en-US', {
				year: 'numeric',
				month: 'long',
				day: 'numeric'
			});
		} catch {
			return dateString;
		}
	}
	
	// Get transfer type badge styles
	function getTransferTypeStyles(type: string): string {
		switch (type.toLowerCase()) {
			case 'signing':
				return 'bg-green-500/20 text-green-600 dark:text-green-400';
			case 'release':
				return 'bg-red-500/20 text-red-600 dark:text-red-400';
			case 'trade':
				return 'bg-blue-500/20 text-blue-600 dark:text-blue-400';
			default:
				return 'bg-gray-500/20 text-gray-600 dark:text-gray-400';
		}
	}
</script>

<svelte:head>
	<title>Transfers - CDLYTICS</title>
</svelte:head>

<div class="min-h-screen">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<h1 class="text-4xl font-bold mb-8 pb-4">TRANSFERS</h1>
		
		{#if error}
			<p class="text-red-500">{error}</p>
		{:else}
			<div class="space-y-4">
				{#if transfers.length > 0}
					{#each transfers as transfer (transfer.id)}
						<div class="bg-theme-secondary p-6 shadow-md shadow-black/10">
							<div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
								<!-- Left: Player Info -->
								<div class="flex items-center space-x-4 flex-1">
									{#if transfer.player?.avatar_url}
										<img
											src={transfer.player.avatar_url}
											alt={transfer.player.gamertag}
											class="w-16 h-16 object-cover shadow-sm"
										/>
									{/if}
									<div class="flex-1">
										<div class="flex items-center gap-3 mb-2">
											<a
												href="/players/{transfer.player_id}"
												class="text-xl font-bold hover:opacity-70 transition-opacity"
											>
												{transfer.player?.gamertag || 'Unknown Player'}
											</a>
											<span class="px-3 py-1 text-xs font-medium {getTransferTypeStyles(transfer.transfer_type)}">
												{transfer.transfer_type.toUpperCase()}
											</span>
										</div>
										
										<!-- Transfer Path -->
										<div class="flex items-center gap-2 text-sm">
											<span class="text-theme-secondary">
												{transfer.from_team?.name || 'Free Agent'}
											</span>
											<span>→</span>
											<span class="font-semibold">
												{transfer.to_team?.name || 'Free Agent'}
											</span>
										</div>
									</div>
								</div>
								
								<!-- Right: Details -->
								<div class="flex flex-col md:items-end gap-2 text-sm">
									<div class="flex items-center gap-4 text-theme-secondary">
										{#if transfer.role}
											<span class="uppercase tracking-wider">{transfer.role}</span>
										{/if}
										{#if transfer.season}
											<span class="uppercase tracking-wider">{transfer.season}</span>
										{/if}
									</div>
									<p class="text-theme-secondary">
										{formatDate(transfer.transfer_date)}
									</p>
								</div>
							</div>
							
							{#if transfer.description}
								<div class="mt-4 pt-4 border-t border-theme">
									<p class="text-sm text-theme-secondary">{transfer.description}</p>
								</div>
							{/if}
						</div>
					{/each}
				{:else}
					<div class="bg-theme-secondary p-8 text-center">
						<p class="text-theme-secondary">No transfers available</p>
					</div>
				{/if}
			</div>
			
			<p class="mt-8 text-theme-secondary text-sm">
				Total Transfers: {transfers.length}
			</p>
		{/if}
	</div>
</div>
