// frontend/src/components/Teams.tsx
import { Link } from "react-router-dom";
import { useApi } from "../hooks/useApi";

interface Team {
  id: number;
  name: string;
  abbreviation: string;
  logo_url: string;
}

const Teams = () => {
  const { data: teams, loading, error } = useApi<Team[]>("/api/v1/teams");

  if (loading) {
    return (
      <div className="min-h-screen bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <p className="text-[#6B7280]">Loading teams...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <p className="text-[#555555]">Error: {error}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="text-4xl font-bold mb-8 pb-4 text-black">TEAMS</h1>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {teams?.map((team) => (
            <Link
              key={team.id}
              to={`/teams/${team.id}`}
              className="p-8 bg-[#F4F4F5] shadow-md shadow-[rgba(0,0,0,0.1)]"
            >
              <div className="flex items-center space-x-4 mb-4">
                {team.logo_url && (
                  <img
                    src={team.logo_url}
                    alt={team.name}
                    className="w-16 h-16 object-contain"
                  />
                )}
                <div>
                  <h2 className="text-xl font-bold text-black">{team.name}</h2>
                  <p className="text-[#6B7280]">{team.abbreviation}</p>
                </div>
              </div>
            </Link>
          ))}
        </div>

        <p className="mt-8 text-[#6B7280] text-sm">
          Total Teams: {teams?.length || 0}
        </p>
      </div>
    </div>
  );
};

export default Teams;

// frontend/src/routes/teams/+page.svelte
<script lang="ts">
	import type { Team } from '$lib/api';
	
	let { data } = $props();
	
	// Use $derived for reactive access to data properties
	const teams = $derived(data.teams as Team[]);
	const error = $derived(data.error as string | null);
</script>

<svelte:head>
	<title>Teams - CDLYTICS</title>
</svelte:head>

<div class="min-h-screen">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<h1 class="text-4xl font-bold mb-8 pb-4">TEAMS</h1>
		
		{#if error}
			<p class="text-red-500">{error}</p>
		{:else}
			<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
				{#each teams as team (team.id)}
					<a
						href="/teams/{team.id}"
						class="p-8 bg-theme-secondary shadow-md shadow-black/10 hover:shadow-lg hover:-translate-y-1 transition-all duration-200"
					>
						<div class="flex items-center space-x-4 mb-4">
							{#if team.logo_url}
								<img
									src={team.logo_url}
									alt={team.name}
									class="w-16 h-16 object-contain"
								/>
							{/if}
							<div>
								<h2 class="text-xl font-bold">{team.name}</h2>
								<p class="text-theme-secondary">{team.abbreviation}</p>
							</div>
						</div>
					</a>
				{/each}
			</div>
			
			<p class="mt-8 text-theme-secondary text-sm">
				Total Teams: {teams.length}
			</p>
		{/if}
	</div>
</div>
