// frontend/src/components/Players.tsx
import { Link } from "react-router-dom";
import { useApi } from "../hooks/useApi";
import type { Player } from "../types";

const Players = () => {
  const { data: players, loading, error } = useApi<Player[]>("/api/v1/players");

  if (loading) {
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <p className="text-gray-400">Loading players...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <p className="text-red-400">Error: {error}</p>
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-4xl font-bold mb-8 pb-4">PLAYERS</h1>

      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="border-b border-gray-800">
              <th className="text-left py-4 text-gray-400 text-sm uppercase tracking-wider">
                Gamertag
              </th>
              <th className="text-left py-4 text-gray-400 text-sm uppercase tracking-wider">
                Name
              </th>
              <th className="text-left py-4 text-gray-400 text-sm uppercase tracking-wider">
                Country
              </th>
              <th className="text-left py-4 text-gray-400 text-sm uppercase tracking-wider">
                Role
              </th>
              <th className="text-center py-4 text-gray-400 text-sm uppercase tracking-wider">
                Status
              </th>
            </tr>
          </thead>
          <tbody>
            {players?.map((player) => (
              <tr
                key={player.id}
                className="border-b border-gray-900 hover:bg-gray-950 transition-colors"
              >
                <td className="py-4">
                  <Link
                    to={`/players/${player.id}`}
                    className="font-semibold hover:text-gray-400"
                  >
                    {player.gamertag}
                  </Link>
                </td>
                <td className="py-4 text-gray-400">
                  {player.first_name && player.last_name
                    ? `${player.first_name} ${player.last_name}`
                    : "—"}
                </td>
                <td className="py-4 text-gray-400">{player.country || "—"}</td>
                <td className="py-4 text-gray-400">{player.role || "—"}</td>
                <td className="py-4 text-center">
                  <span
                    className={
                      player.is_active ? "text-white" : "text-gray-600"
                    }
                  >
                    {player.is_active ? "Active" : "Inactive"}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-8 text-gray-400 text-sm">
        Total Players: {players?.length || 0}
      </p>
    </div>
  );
};

export default Players;

// frontend/src/routes/players/+page.svelte
<script lang="ts">
	import type { Player } from '$lib/api';
	
	// In Svelte 5, we get data from load() via $props()
	// This is equivalent to useLoaderData() in React Router
	let { data } = $props();
	
	// Use $derived for reactive access to data properties
	// This ensures the values update if data changes
	const players = $derived(data.players as Player[]);
	const error = $derived(data.error as string | null);
</script>

<svelte:head>
	<title>Players - CDLYTICS</title>
</svelte:head>

<div class="min-h-screen">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<h1 class="text-4xl font-bold mb-8 pb-4">PLAYERS</h1>
		
		{#if error}
			<p class="text-red-500">{error}</p>
		{:else}
			<div class="overflow-x-auto">
				<table class="w-full">
					<thead>
						<tr class="border-b border-theme">
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Gamertag
							</th>
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Name
							</th>
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Country
							</th>
							<th class="text-left py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Role
							</th>
							<th class="text-center py-4 text-theme-secondary text-sm uppercase tracking-wider">
								Status
							</th>
						</tr>
					</thead>
					<tbody>
						{#each players as player (player.id)}
							<tr class="border-b border-theme hover:bg-theme-secondary/50 transition-colors">
								<td class="py-4">
									<a 
										href="/players/{player.id}" 
										class="font-semibold hover:opacity-70 transition-opacity"
									>
										{player.gamertag}
									</a>
								</td>
								<td class="py-4 text-theme-secondary">
									{player.first_name && player.last_name
										? `${player.first_name} ${player.last_name}`
										: '—'}
								</td>
								<td class="py-4 text-theme-secondary">
									{player.country || '—'}
								</td>
								<td class="py-4 text-theme-secondary">
									{player.role || '—'}
								</td>
								<td class="py-4 text-center">
									<span class={player.is_active ? '' : 'text-theme-secondary'}>
										{player.is_active ? 'Active' : 'Inactive'}
									</span>
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
			
			<p class="mt-8 text-theme-secondary text-sm">
				Total Players: {players.length}
			</p>
		{/if}
	</div>
</div>
